# Generated by Django 4.2.1 on 2023-06-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=100)),
                ('email', models.CharField(default='noemail@noemail.com', max_length=75)),
                ('password', models.CharField(default='1234', max_length=32)),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('stock', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.seller')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.user')),
            ],
        ),
    ]
